apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: snowflake-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: snowflake-id-generator
  template:
    metadata:
      labels:
        app: snowflake-id-generator
    spec:
      initContainers:
        - name: init-config-generator
          image: alpine:latest
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              RANDOM_ID=$(echo $(( $RANDOM % 32 )))
              echo "Генерирую Worker ID: $RANDOM_ID"
              echo "snowflake-settings.worked-id=$RANDOM_ID" > /app/config/dynamic.properties
          volumeMounts:
            - name: worker-config-volume
              mountPath: /app/config
      containers:
        - name: snowflake-id-generator
          image: meirzhan250/snowflake-id-generator:1.0.2
          envFrom:
            - configMapRef:
                name: snowflake-config
          env:
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: "file:/app/config/"
          volumeMounts:
            - mountPath: /app/config
              name: worker-config-volume
              readOnly: true
            - mountPath: /config
              name: snowflake-config-volume
              readOnly: true
          livenessProbe:
            httpGet:
              path: /management/health/liveness
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /management/health/readiness
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
      volumes:
        - name: worker-config-volume
          emptyDir: {}
        - name: snowflake-config-volume
          configMap:
            name: snowflake-config
