apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: snowflake-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: snowflake-id-generator
  template:
    metadata:
      labels:
        app: snowflake-id-generator
    spec:
      containers:
        - name: snowflake-id-generator
          image: meirzhan250/snowflake-id-generator:1.0.0
          livenessProbe:
            httpGet:
              path: /management/health/liveness
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /management/health/readiness
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
